services:
  aquant-sdk-python:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: aquant-sdk-python
    tty: true
    stdin_open: true
    ports:
      - "8000:8000" 
    volumes:
      - ./:/app  
    networks:
      - aquant-net

networks:
  aquant-net:
    external: true
