name: Deploy to AWS EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          if [ ! -d "/var/www/aquant.auth.api" ]; then
              git clone git@github.com:aquant-co/aquant.auth.api.git /var/www/aquant.auth.api
          else
              cd /var/www/aquant.auth.api
              git reset --hard
              git pull origin main
          fi
          cd /var/www/aquant.auth.api
          # docker compose down
          docker compose up -d --build
          EOF
